### ISSUE TITLE
Error whrn running helloworld.py

### ISSUE THREAD

**Issue by Kartoffelchen** [owl-project/NVISII#115]
My Nvidia driver is 460.73.1, system is Ubuntu 18.04.

installation:
```bash
pip install nvisii
```

To run the 00.helloworld.py, and the error was like this:
```bash
terminate called after throwing an instance of 'std::runtime_error'
what(): Error: Failed to create OpenGL window. Minimum OpenGL version is 4.3.
Aborted (core dumped)
```

**Comment by TontonTremblay** [comment]
can you pass `headless=True` in the initialize function. It sounds like you are not running the right version of opengl for the interactive window. Maybe look into upgrading it? https://medium.com/geekculture/a-beginners-guide-to-setup-opengl-in-linux-debian-2bfe02ccd1e

**Comment by Kartoffelchen** [comment]
Thanks, it truly worked!
