### ISSUE TITLE
Gamma correction for depth image option

### ISSUE THREAD

**Issue by awesome-aj0123** [owl-project/NVISII#118]
Hello, I was recently working with NViSII and was trying to get the raw pixels for the images, and it was brought to my attention that this data does not include for gamma correction. I was just wondering if anyone could potentially shed some light on how to add the correction manually or if this could be added as a feature to NViSII directly. Thank you so much for the help!

**Comment by natevm** [comment]
Hi Abhishek,

You should never use gamma correction on a depth image. Gamma correction is a tone mapping process meant only for final color images. 

For depth segmentations, I recommend saving images using either .exr or .hdr, as .png will lose precision.
