### ISSUE TITLE
how to show the world coordinate system?

### ISSUE THREAD

**Issue by ctxqlxs** [owl-project/NVISII#120]
like this(blender):
![image](https://user-images.githubusercontent.com/27945719/130176337-14ce85ac-d430-4324-aeac-d06a4500c8fb.png)
or this(pybullet):
![image](https://user-images.githubusercontent.com/27945719/130176370-8120e09b-3518-42d8-860d-74531e0a4a45.png)

**Comment by natevm** [comment]
We do not natively support rendering guizmos like these in nvisii. 

I suggest you render an object like this: https://sketchfab.com/3d-models/axis-136a7d2eb94b40d496577533b01d163c

See the examples on how to render objects.
