### ISSUE TITLE
material setting

### ISSUE THREAD

**Issue by ctxqlxs** [owl-project/NVISII#121]
how to set plastic material?
like this:
![image](https://user-images.githubusercontent.com/27945719/130213494-3554ac19-c6eb-4ec6-8e78-1acbcc1f17bb.png)

**Comment by natevm** [comment]
I suggest checking out examples 17 and 18 to learn how to create the material that you  
want. We render a bunch of different objects with different materials there, and you can pick which configuration looks closer to what you’re after.

https://github.com/owl-project/NVISII/blob/master/examples/17.materials_visii_interactive.py

https://github.com/owl-project/NVISII/blob/master/examples/18.materials.py

in general, a plastic material can be made by creating and assigning a material component with roughness = 0, metallic = 0, and transmission = 0.
