### ISSUE TITLE
`set_intrinsics` function documentation

### ISSUE THREAD

**Issue by ArthurAllshire** [owl-project/NVISII#136]
In the docs [here](https://nvisii.com/camera.html?highlight=set_projection#nvisii.camera.set_intrinsics), the `set_intrinsics` function states

```
fx (float) – X-axis focal length in meters.
fy (float) – Y-axis focal length in meters.
```

However I believe that this is a typo and they should be in pixels? When I put in F/L in meters I get very strange images, whereas when I put in pixels things work perfectly.

**Comment by natevm** [comment]
Sorry for the late response. Been drowning in other projects.

We essentially stole from the intrinsics camera code here:

https://pyrender.readthedocs.io/en/latest/generated/pyrender.IntrinsicsCamera.html

Their documentation states that fx and fy should be in meters. Do you also disagree with the pyrender documentation? I'm not sure who to trust to be honest.

**Comment by natevm** [comment]
I haven't heard back on this issue in a while, so I'm closing for the time being. Feel free to reopen if you find the time. :)

**Comment by murrdpirate** [comment]
@natevm `fx` and `fy` should generally be in pixels (and always match the units used for `cx` and `cy`). It looks like pyrender updated their documentation to pixels.

**Comment by ancientghost** [comment]
> @natevm `fx` and `fy` should generally be in pixels (and always match the units used for `cx` and `cy`). It looks like pyrender updated their documentation to pixels.

Sure, it's updated, `fx` and `fy` should be in pixels, refer to this [here](https://pyrender.readthedocs.io/en/latest/generated/pyrender.IntrinsicsCamera.html?highlight=IntrinsicsCamera).
