### ISSUE TITLE
Data generation scripts for RTMV: A Ray-Traced Multi-View Synthetic Dataset for Novel View Synthesis

### ISSUE THREAD

**Issue by zubair-irshad** [owl-project/NVISII#145]
Hi there, great work! 

Any plans on releasing the data generation scripts for [RTMV: A Ray-Traced Multi-View Synthetic Dataset for Novel View Synthesis](https://arxiv.org/pdf/2205.07058.pdf)? Thanks in advance.

**Comment by natevm** [comment]
@TontonTremblay is the guy to ask for this one. I don't personally see why this couldn't happen though. :)

**Comment by zubair-irshad** [comment]
Thanks! I got in touch with @TontonTremblay over email.
