### ISSUE TITLE
Is NVISII compatible with Tesla K80 gpus?

### ISSUE THREAD

**Issue by liswp** [owl-project/NVISII#163]
Is NVISII compatible with Tesla K80 gpus? It doesn't seem to be. 

Please let us know. Many thanks.

**Comment by natevm** [comment]
I believe Kepler GPUs like your Tesla K80 are no longer supported by OptiX. That’s a fairly old card at this point, almost 10 years old, so those GPUs don’t really support all that’s required to effectively ray trace images.

GPUs must be Maxwell or newer
