### ISSUE TITLE
Could this still be used for generating synthetic data for DOPE?

### ISSUE THREAD

**Issue by KennethEladistu** [owl-project/NVISII#175]
Hi can I still use this one to generate my synthetic data for my own model and load it in DOPE?

**Comment by TontonTremblay** [comment]
Yes just follow the instructions on the dope repo. Sorry phone answer.

**Comment by KennethEladistu** [comment]
thank you for the reply!

**Comment by TontonTremblay** [comment]
I am sorry, i just noticed that Jeff removed the script, https://github.com/NVlabs/Deep_Object_Pose/tree/128631a23c827d2091cfd103c03c8c3a93fc6134/scripts/nvisii_data_gen you can find it here, i will add a link to the repo.

**Comment by TontonTremblay** [comment]
Ok it is still there: https://github.com/NVlabs/Deep_Object_Pose/tree/master/data_generation/nvisii_data_gen

**Comment by KennethEladistu** [comment]
> Ok it is still there: https://github.com/NVlabs/Deep_Object_Pose/tree/master/data_generation/nvisii_data_gen

thank you for the help!
