### ISSUE TITLE
Weird error message when driver is out of date

### ISSUE THREAD

**Issue by n8vm** [owl-project/NVISII#40]
When the user has an outdated driver (less than 450), they're given the following error message:

Optix call (optixInit()) failed with code 7801 (line 150)
terminate called without an active exception
Aborted (core dumped)

We should give a more helpful error message to guide users to upgrade their driver.

**Comment by zhuyifengzju** [comment]
I am currently using driver 450.51 with cuda 11.0. It seems that the v1.0 throws the same error. Is there any solution to this? Thanks!

**Comment by n8vm** [comment]
Hi @zhuyifengzju! I bet you have nvisii 1.0.72 installed, which I believe requires 460. Can you try doing pip install nvisii=1.0.70 and see if that works? (Fwiw, the last two numbers in the nvisii version specify which version of OptiX was compiled. Newer OptiX versions support more features, but require newer drivers)

**Comment by zhuyifengzju** [comment]
Yeah, that works. Thanks!

**Comment by n8vm** [comment]
Nice! Closing, but feel free to open new issues if you run into more problems.
