### ISSUE TITLE
no CUDA capable devices found!

### ISSUE THREAD

**Issue by hetolin** [owl-project/NVISII#91]
Hi, I am trying to run the code in the /example folder, but it throws the error like that:
`
terminate called after throwing an instance of 'std::runtime_error'
what():  #owl: no CUDA capable devices found!
`

the system configuration are following: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
NVIDIA-SMI 418.56       
Driver Version: 418.56      
CUDA Version: 10.1

**Comment by n8vm** [comment]
Hi @hetolin,

looks like your driver version is a little too old. The earliest driver we support is R435 (using pip install nvisii==1.0.70).

**Comment by hetolin** [comment]
Thank you for your prompt reply, I will have a try

**Comment by n8vm** [comment]
Hi @hetolin , 
Were you able to solve your issue?

**Comment by n8vm** [comment]
Closing for now due to inactivity. Please let me know if you're still having issues.
